- name: start ocp-bootstrap
  virt:
    name: ocp-bootstrap
    state: running

- name: wait for ocp-bootstrap VM about 10 mins
  pause:
    minutes: 20

- name: start ocp-master nodes
  virt:
    name: "{{ item }}"
    state: running
  loop:
    - ocp-master-0
    - ocp-master-1
    - ocp-master-2

- name: wait for OCP Master VMs about 20 mins 
  pause:
    minutes: 30
 
- name: start ocp-worker nodes
  virt:
    name: "{{ item }}"
    state: running
  loop:
    - ocp-node-0
    - ocp-node-1

- name: start ocp-router nodes
  virt:
    name: "{{ item }}"
    state: running
  loop:
    - ocp-router-0
    - ocp-router-1
  when: router_node_enable == "yes"

- name: start ocp-infra nodes
  virt:
    name: "{{ item }}"
    state: running
  loop:
    - ocp-infra-0
    - ocp-infra-1
  when: infra_node_enable == "yes"

- name: wait for OCP worker node VMs about 20 mins 
  pause:
    minutes: 30
