---
# tasks file for post-cleanup-vms
#
- name: RWX storage no has the cluster
  shell: oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"emptyDir":{}}}}'
