- name: install dhcpd
  package:
    name: "{{ item }}"
    state: present
  loop:
    - dhcp-common
    - dhcp

- name: copy dhcpd.conf file 
  copy:
    src: ocp-dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf

- name: start and enable to the dhcpd service
  systemd:
    name: dhcpd
    state: started
    enabled: yes
