---
- name: approve all the csr and wait a minutes the worker and infra nodes can be seen.
  shell: "oc get csr -o name | xargs oc adm certificate approve"

- pause:
    minutes: 5
    prompt: wait a approve all the crs about 5 mins
