---
- name: aa                                                                                                                                   
  shell: "oc get csr | grep -i pending | cut -f 1 -d ' ' | wc -l"
  register: csr_list


- name: approve all the csr and wait a minutes the worker and infra nodes can be seen.
  block:
  - shell: "oc get csr | grep -i pending | cut -f 1 -d ' ' | xargs oc adm certificate approve"
  - pause:
      minutes: 5
      prompt: wait a approve all the CRS about 5 mins
  when: csr_list.stdout != "0" 

