- name: copy a utility kickstart file on /tmp
  copy:
    src: "{{ item }}"
    dest: /tmp/
  loop:
    - utility.ks
    - httpd.py

- name: build a utility node
  tags: build-utility
  shell: qemu-img create -f qcow2 /var/lib/libvirt/images/{{ ocp_cluster_name }}-utility.qcow2 100G

- name: create a utility node
  tags: build-utility
  shell: virt-install --name {{ ocp_cluster_name }}-utility -r 4096 --vcpus 2 -l http://mirror.kakao.com/centos/7/os/x86_64/ --network network={{ ocp_vir_net }} --graphics spice -v --disk=path=/var/lib/libvirt/images/{{ ocp_cluster_name }}-utility.qcow2,format=qcow2 --noautoconsole --initrd-inject=/tmp/utility.ks -x "ks=file:/utility.ks" 

- pause:
    minutes: 10

- name: customized the utility node
  tags: inject-utility
  shell: |
    virt-customize -m 2048 -a /var/lib/libvirt/images/{{ ocp_cluster_name }}-utility.qcow2 \
    --uninstall cloud-init \
    --ssh-inject root:string:'{{ ocp_public_keyfile }}' --selinux-relabel \
    --run-command 'mkdir -p /tmp/root/' --upload /tmp/httpd.py:/tmp/root


